config/routes.rb
Rails.application.routes.draw do
  
  
  resources :errors_logs
  resources :tickets
  resources :basic_data
  
  root 'pages#homepage'
  get 'pages/visitor_login'
  get 'pages/home'
  get 'pages/contact_us'
  get 'pages/mission'
  get 'pages/about_us'
  get 'pages/human_cadres'
  get 'pages/services'
  get 'pages/customers'
  get 'pages/news'
  get 'pages/details'
  get 'pages/our_company'
  get 'pages/disclaimer'
  get 'pages/terms_of_use'
  get 'pages/privacy_policy'
  get 'pages/change_lang'
  get 'pages/error'
  


  
  get "unlockaccount" => "users#unlockaccount"

  resources :visitor_services, only: [:new, :create]
  resources :users, except: [:index,:destroy]
  resources :audit_logs, only: [:create]
 
  get 'edit_password' => "users#edit_password"
  match 'confirm_signin', to: 'users#confirm_signin', via: %i(get post)
  get 'resend_code' => "users#resend_confirmation_code"
  get 'models' => "users#models"
  get 'reports' => "users#reports"
  get 'required_files' => "users#required_files"
  patch 'update_file' => "users#update_file"
  get 'notifications' => "users#notifications"
  get 'show_notification' => "users#show_notification"
  post 'send_email' => "visitor_services#send_email"



  


  #scope path: 'admin', module: 'admin' do
  namespace :admin do
    match 'add-user', to: 'members#add_user', via: %i(get post)
    get 'admins' => "members#admins"
    get 'users/search' => "members#user_search"
    get 'admins/search' => "members#admin_search"
    get 'visitor_services/search' => "visitor_services#search"
    get 'messages/search' => "messages#ticket_search"
    get 'dashboard' => "pages#dashboard"
    #get 'news' => "pages#news"

    get 'delete_image' => "contents#delete_image"
    get 'delete_news_image' => "news#delete_news_image"
    get 'delete_mission_image' => "our_missions#delete_mission_image"
    get 'delete_customer_image' => "premium_customers#delete_customer_image"





    #resources :users
    resources :audit_logs, only: [:index, :show]
    resources :visitor_services
    resources :contents, except: [:new, :create, :destroy]
    resources :premium_customers
    resources :our_missions, except: [:new, :create, :destroy]
    resources :news
    resources :models
    resources :required_files
    resources :users_basic_data
    resources :reports
    resources :members
    resources :messages
    resources :notifications






  end
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/required_file.rb
class RequiredFile < ApplicationRecord
    has_one_attached :file
    enum status: { created: 0, pending: 1, accepted: 2, rejected: 3 }
    belongs_to :user ,:foreign_key => "user_id"

    

    def self.to_csv(options = {})
      attributes = %w{id name description status created_at}    
        CSV.generate(headers: true) do |csv|
          csv << attributes    
          all.each do |required_files|
            csv << [required_files.id, required_files.user.username, required_files.description, required_files.status, required_files.created_at]
          end
        end
    end

end

app/controllers/admin/required_files_controller.rb
class Admin::RequiredFilesController < Admin::AdminController
  before_action :set_required_file, only: [:show, :edit, :update, :destroy]

  # GET /required_files
  # GET /required_files.json
  def index
    @required_files = RequiredFile.all.includes(:user)
    respond_to do |format|
      format.html
      format.csv { send_data @required_files.to_csv }
      format.xls { send_data @required_files.to_csv(col_sep: "\t") }
    end
  end

  # GET /required_files/1
  # GET /required_files/1.json
  def show
  end

  # GET /required_files/new
  def new
    @required_file = RequiredFile.new
  end

  # GET /required_files/1/edit
  def edit
  end

  # POST /required_files
  # POST /required_files.json
  def create
    @required_file = RequiredFile.new(required_file_params)
    @required_file.status == "created"

    respond_to do |format|
      if @required_file.save
        format.html { redirect_to admin_required_file_path(@required_file), notice: 'Required file was successfully created.' }
        format.json { render :show, status: :created, location: @required_file }
      else
        format.html { render :new }
        format.json { render json: @required_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /required_files/1
  # PATCH/PUT /required_files/1.json
  def update
    respond_to do |format|
      if @required_file.update(required_file_params)
        format.html { redirect_to admin_required_file_path(@required_file), notice: 'Required file was successfully updated.' }
        format.json { render :show, status: :ok, location: @required_file }
      else
        format.html { render :edit }
        format.json { render json: @required_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /required_files/1
  # DELETE /required_files/1.json
  def destroy
    @required_file.destroy
    respond_to do |format|
      format.html { redirect_to admin_required_files_url, notice: 'Required file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_required_file
      @required_file = RequiredFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def required_file_params
      params.require(:required_file).permit(:user_id, :description, :status, :file)
    end
end

app/helpers/required_files_helper.rb
module RequiredFilesHelper
end

app/views/admin/required_files/_form.html.erb
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-6">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t("New Required File")%></h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <%= form_for @required_file , :url => admin_required_files_path do |form| %>
          <% if @required_file.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@required_file.errors.count, "error") %> prohibited this required_file from being saved:</h2>
                <ul>
                  <% @required_file.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
            </div>
          <% end %>
          <div class="box-body">
            <div class="form-group">
              <label><%= t("Name") %></label>
              <%= form.select(:user_id,  options_for_select(User.where(:role_id => "user").all.collect {|p| [ p.email, p.id ] }) ,{:include_blank =>  'choose from list'} ,  :class => 'form-control' ) %>
            </div>
            <div class="form-group">
              <label><%= t("details") %></label>
              <%= form.text_area :description, :class => "form-control", :placeholder => t("Details"), :required => true %>
            </div>
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <button type="submit" class="btn btn-primary" id="submit" >Submit</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/admin/required_files/edit.html.erb
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-6">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t("Edit Required File")%></h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <%= form_for @required_file , :url => admin_required_file_path do |form| %>
            <% if @required_file.errors.any? %>
                <div id="error_explanation">
                <h2><%= pluralize(@required_file.errors.count, "error") %> prohibited this required_file from being saved:</h2>
                    <ul>
                    <% @required_file.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>
          <div class="box-body">
            <div class="form-group">
              <label><%= t("Name") %></label>
              <%= form.select(:user_id,  options_for_select(User.where(:role_id => "user").all.collect {|p| [ p.email, p.id ] }) ,{:include_blank =>  'choose from list'} ,  :class => 'form-control' ) %>
            </div>
            <div class="form-group">
              <label><%= t("details") %></label>
              <%= form.text_area :description, :class => "form-control", :placeholder => t("Details"), :required => true %>
            </div>
            <div class="form-group">
              <label><%= t("Status") %></label>
               <%= form.select(:status, options_for_select([[t("accepted"),"accepted"],[t("rejected"),"rejected"]], :selected => form.object.status), {},:class => 'form-control')%>
            </div>
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <button type="submit" class="btn btn-primary" id="submit" >Submit</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>


<%= link_to t('Show'), admin_required_file_path(@required_file) %> |
<%= link_to t('Back'), admin_required_files_path %>

app/views/admin/required_files/index.html.erb
 <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
          
            <div class="box-header">
              <h3 class="box-title"><%= t("Required Files") %></h3>
              <%= link_to "Export To Excel", admin_required_files_path(format: "xls"), :class => "btn btn-primary waves-effect waves-light  text-center" %>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th><%= t("UserName") %></th>
                  <th><%= t("Required Data") %></th>
                  <th><%= t("status") %></th>
                  <th><%= t("file") %></th>
                  <th><%= t("created_at") %></th>
                  <th><%= t("updated_at") %></th>
                  <th colspan="3"></th>
                </tr>
                </thead>
                <tbody>
                  <% @required_files.each do |required_file| %>
                    <tr>
                      <td><%= required_file.user.username %></td>
                      <td><%= required_file.description %></td>
                      <td><%= required_file.status %></td>
                      <% if required_file.file.attached? %>
                        <td><%= link_to "download", rails_blob_path(required_file.file, disposition: 'download') %></td>
                      <% else %>
                         <td></td>
                      <% end %>
                      <td><%= required_file.created_at.strftime('%H:%M:%S%p at %d/%m/%Y ')  %></td>
                      <td><%= required_file.updated_at.strftime('%H:%M:%S%p at %d/%m/%Y ')  %></td>
                      <td><%= link_to t("Show"), admin_required_file_path(required_file) %></td>
                      <td><%= link_to t("Edit"), edit_admin_required_file_path(required_file) %></td>
                      <td><%= link_to t("Destroy"), admin_required_file_path(required_file), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>               
                </tbody> 
              </table>
            </div>
          </div>
        </div>
      </div>
  </section>


<br>
<%= link_to t('Back'), admin_dashboard_path %>| <%= link_to  t("New required file"), new_admin_required_file_path %>

app/views/admin/required_files/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
        <%# @posts=params[:posts] %>

    <Table>
      <Row>
        <Cell><Data ss:Type="String"> ID</Data></Cell>
        <Cell><Data ss:Type="String">user_id</Data></Cell>
        <Cell><Data ss:Type="String"> description</Data></Cell>
        <Cell><Data ss:Type="String">status</Data></Cell>
        <Cell><Data ss:Type="String"> created_at</Data></Cell>
        <Cell><Data ss:Type="String">updated at</Data></Cell>
        
      </Row>
    <% @required_files.each do |required_file| %>
      <Row>
        <Cell><Data ss:Type="String"><%= required_file.id %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= required_file.user.username %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= required_file.description %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= required_file.status %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= required_file.created_at %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= required_file.updated_at %></Data></Cell>


      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/required_files/new.html.erb
<%= render 'form', required_file: @required_file %>

<%= link_to t('Back'), admin_required_files_path %>

app/views/admin/required_files/show.html.erb
 <section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title"><%= t("Details") %></h3>
        </div><br>         
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead></thead>
                <tbody>
                    <tr>
                      <td><%= t("UserName") %></td>
                      <td><%= @required_file.user.username %></td>                      
                    </tr>
                    <tr>
                      <td><%= t("Description") %></td>
                      <td><%= @required_file.description %></td>                      
                    </tr>
                    <tr>
                      <td><%= t("Status") %></td>
                      <td><%= @required_file.status %></td>                      
                    </tr>
                  <% if @required_file.file.attached? %>
                    <tr>
                      <td><%= t("file") %></td>
                      <td><%= link_to "download", rails_blob_path(@required_file.file, disposition: 'download') %></td>                      
                    </tr>
                  <% end %>
                    <tr>
                      <td><%= t("created_at") %></td>
                      <td><%= @required_file.created_at %></td>                      
                    </tr>
                    <tr>
                      <td><%= t("updated_at") %></td>
                      <td><%= @required_file.updated_at %></td>                      
                    </tr>
                    <tr>
                      <td></td>
                      <td><%= link_to t('Edit'), edit_admin_required_file_path(@required_file) %> | 
                          <%= link_to t('Back'), admin_required_files_path %>
                      </td>                      
                    </tr>
                </tbody> 
              </table>
            </div>
          </div>
        </div>
      </div>
  </section>