config/routes.rb
Rails.application.routes.draw do
  
  
  resources :errors_logs
  resources :tickets
  resources :basic_data
  
  root 'pages#homepage'
  get 'pages/visitor_login'
  get 'pages/home'
  get 'pages/contact_us'
  get 'pages/mission'
  get 'pages/about_us'
  get 'pages/human_cadres'
  get 'pages/services'
  get 'pages/customers'
  get 'pages/news'
  get 'pages/details'
  get 'pages/our_company'
  get 'pages/disclaimer'
  get 'pages/terms_of_use'
  get 'pages/privacy_policy'
  get 'pages/change_lang'
  get 'pages/error'
  


  
  get "unlockaccount" => "users#unlockaccount"

  resources :visitor_services, only: [:new, :create]
  resources :users, except: [:index,:destroy]
  resources :audit_logs, only: [:create]
 
  get 'edit_password' => "users#edit_password"
  match 'confirm_signin', to: 'users#confirm_signin', via: %i(get post)
  get 'resend_code' => "users#resend_confirmation_code"
  get 'models' => "users#models"
  get 'reports' => "users#reports"
  get 'required_files' => "users#required_files"
  patch 'update_file' => "users#update_file"
  get 'notifications' => "users#notifications"
  get 'show_notification' => "users#show_notification"
  post 'send_email' => "visitor_services#send_email"



  


  #scope path: 'admin', module: 'admin' do
  namespace :admin do
    match 'add-user', to: 'members#add_user', via: %i(get post)
    get 'admins' => "members#admins"
    get 'users/search' => "members#user_search"
    get 'admins/search' => "members#admin_search"
    get 'visitor_services/search' => "visitor_services#search"
    get 'messages/search' => "messages#ticket_search"
    get 'dashboard' => "pages#dashboard"
    #get 'news' => "pages#news"

    get 'delete_image' => "contents#delete_image"
    get 'delete_news_image' => "news#delete_news_image"
    get 'delete_mission_image' => "our_missions#delete_mission_image"
    get 'delete_customer_image' => "premium_customers#delete_customer_image"





    #resources :users
    resources :audit_logs, only: [:index, :show]
    resources :visitor_services
    resources :contents, except: [:new, :create, :destroy]
    resources :premium_customers
    resources :our_missions, except: [:new, :create, :destroy]
    resources :news
    resources :models
    resources :required_files
    resources :users_basic_data
    resources :reports
    resources :members
    resources :messages
    resources :notifications






  end
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/premium_customer.rb
class PremiumCustomer < ApplicationRecord
    has_one_attached :image
    enum category: { customer_opinions: 0, our_partners: 1 }
    validate :attachment_type


    def attachment_type
        if image.attached? 
            if !image.attachment.blob.content_type.in?(%w(image/png image/jpg image/jpeg image/tiff image/tif))
                errors.add(:image, I18n.t('not_allowed_file_type'))
            elsif image.blob.byte_size > (2097152) 
                errors.add(:image, I18n.t('max_size_2MB'))
            end
        end
    end

end

app/controllers/admin/premium_customers_controller.rb
class Admin::PremiumCustomersController < Admin::AdminController

  before_action :set_premium_customer, only: [:show, :edit, :update, :destroy]

  # GET /premium_customers
  # GET /premium_customers.json
  def index
    @premium_customers = PremiumCustomer.where(:category => params[:type].to_s).all
  end


  # GET /premium_customers/1
  # GET /premium_customers/1.json
  def show
  end

  # GET /premium_customers/new
  def new
    @premium_customer = PremiumCustomer.new
  end

  # GET /premium_customers/1/edit
  def edit
  end

  # POST /premium_customers
  # POST /premium_customers.json
  def create
    @premium_customer = PremiumCustomer.new(premium_customer_params)

      if @premium_customer.save
        redirect_to admin_premium_customer_path(@premium_customer), notice: 'Premium customer was successfully created.'
      else
        render :new 
      end
  end

  # PATCH/PUT /premium_customers/1
  # PATCH/PUT /premium_customers/1.json
  def update
      if @premium_customer.update(premium_customer_params)
        redirect_to admin_premium_customer_path(@premium_customer), notice: t('Data was successfully updated')
      else
        render :edit
      end
  end

  def delete_customer_image
    @customerimage = PremiumCustomer.find(params[:id])
    @customerimage.image.purge
    redirect_to admin_premium_customer_path(@customerimage), notice: t('Image was deleted')
  end

  # DELETE /premium_customers/1
  # DELETE /premium_customers/1.json
  def destroy
    @premium_customer.image.purge_later
    @premium_customer.destroy
      redirect_to admin_premium_customers_url, notice: 'Premium customer was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_premium_customer
      @premium_customer = PremiumCustomer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def premium_customer_params
      params.require(:premium_customer).permit(:key, :name_ar, :name_en, :description_ar, :description_en, :status, :category, :image)
    end
end

app/helpers/premium_customers_helper.rb
module PremiumCustomersHelper
end

app/views/admin/premium_customers/_form.html.erb
<section class="content">
  <div class="row">
    <!-- left column -->
      <div class="col-md-6">
        <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"><%= t("Premium Customers")%></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <%= form_for @premium_customer , :url => admin_premium_customer_path do |form| %>
              <% if @premium_customer.errors.any? %>
                <div id="error_explanation">
                  <%= pluralize(@premium_customer.errors.count, t("error")) %> <%= t("prohibited from being saved") %>
                    <ul>
                      <% @premium_customer.errors.full_messages.each do |message| %>
                         <li><%= message %></li>
                      <% end %>
                    </ul>
                </div>
              <% end %> 
              <div class="box-body">

              <div class="form-group">
                  <label for="category"><%= t("status") %></label>
                  <%= form.select(:category, options_for_select([[t("customer_opinions"),"customer_opinions"],[t("our_partners"),"our_partners"]], :selected => form.object.category), {},:class => 'form-control')%>
                </div>

                <div class="form-group">
                  <label for="exampleInputkey"><%= t("Key") %></label>
                  <%= form.text_field :key, :class => "form-control", :placeholder => t("Key"), :required => true %>
                </div>

                <div class="form-group">
                  <label for="exampleInputname"><%= t("Name") %></label>
                    <%= form.text_field :name_ar, :class => "form-control", :placeholder => t("Name"), :required => true %>
                </div>

                <div class="form-group">
                  <label for="exampleInputname"><%= t("Name") %></label>
                    <%= form.text_field :name_en, :class => "form-control", :placeholder => t("Name"), :required => true %>
                </div>

                <div class="form-group">
                  <label for="exampleInputdetails"><%= t("Details") %></label>
                    <%= form.text_field :description_ar, :class => "form-control", :placeholder => t("Details"), :required => true %>
                </div>

                <div class="form-group">
                  <label for="exampleInputdetails"><%= t("Details") %></label>
                    <%= form.text_field :description_en, :class => "form-control", :placeholder => t("Details"), :required => true %>
                </div>

                <div class="checkbox">
                  <label for="exampleInputstatus"><%= t("Status") %></label>
                    <%= form.check_box :status,{},"true","false" %>                  
                </div>

                <div class="form-group">
                  <label><%= t("Image") %></label>
                  <%= form.file_field :image %>
                </div>

              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                    <button type="submit" class="btn btn-primary" id="submit" >Submit</button>
              </div>
            <% end %>
          </div>
      </div>
  </div>
</section>

app/views/admin/premium_customers/edit.html.erb
<%= render 'form', premium_customer: @premium_customer %>

<%= link_to t('Show'), admin_premium_customer_path(@premium_customer) %> |
<%= link_to t('Back'), admin_premium_customers_path %>

app/views/admin/premium_customers/index.html.erb
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
          
        <div class="box-header">
          <h3 class="box-title"><% if params[:type] == "our_partners" %>
            <%= t("our_partners") %></h3>
          <% else %>
            <%= t("customer_opinions") %></h3>
          <% end %>
          
        </div>
            
        <!-- /.box-header -->
          <div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th><%= t("ar_name")%></th>
                  <th><%= t("en_name")%></th>
                  <th><%= t("Status") %></th> 
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @premium_customers.each do |premium_customer| %>
                  <tr>
                      <td><%= premium_customer.name_ar %></td>
                      <td><%= premium_customer.name_en %></td>
                      <td><%= premium_customer.status %></td>
                      <td><%= link_to t("Show"), admin_premium_customer_path(premium_customer) %></td>
                      <td><%= link_to t("Edit"), edit_admin_premium_customer_path(premium_customer) %></td>
                      <td><%= link_to t("Destroy"), admin_premium_customer_path(premium_customer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>               
                </tbody> 
              </table>
            </div>
          </div>
        </div>
      </div>
  </section>


<br>
<% if params[:type] == "our_partners" %>
  <%= link_to t('New Partner'), new_admin_premium_customer_path(type: "our_partners") %>|
<% else %>
  <%= link_to t('New Customer Opinion'), new_admin_premium_customer_path(type: "customer_opinions") %>|
<% end %>

<%= link_to t('Back'), admin_dashboard_path %>

app/views/admin/premium_customers/new.html.erb
<section class="content">
  <div class="row">
    <!-- left column -->
      <div class="col-md-6">
        <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">
                <% if params[:type] == "our_partners" %>
                  <%= t("'New Partner") %></h3>
                <% else %>
                  <%= t("New Customer Opinion") %></h3>
                <% end %>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <%= form_for @premium_customer , :url => admin_premium_customers_path do |form| %>
              <% if @premium_customer.errors.any? %>
                <div id="error_explanation">
                  <%= pluralize(@premium_customer.errors.count, t("error")) %> <%= t("prohibited from being saved") %>
                    <ul>
                      <% @premium_customer.errors.full_messages.each do |message| %>
                         <li><%= message %></li>
                      <% end %>
                    </ul>
                </div>
              <% end %> 
              <div class="box-body">

              <div class="form-group4">
                <label for="name"><%= t(params[:type]) %></label>
                <%= form.hidden_field :category %>         
              </div>

                <div class="form-group">
                  <label for="exampleInputkey"><%= t("Key") %></label>
                  <%= form.text_field :key, :class => "form-control", :placeholder => t("Key"), :required => true %>
                </div>

                 <div class="form-group">
                  <label for="exampleInputname"><%= t("ar_name") %></label>
                    <%= form.text_field :name_ar, :class => "form-control", :placeholder => t("ar_name"), :required => true %>
                </div>

                <div class="form-group">
                  <label for="exampleInputname"><%= t("en_name") %></label>
                    <%= form.text_field :name_en, :class => "form-control", :placeholder => t("en_name"), :required => true %>
                </div>

                <div class="form-group">
                  <label for="exampleInputdetails"><%= t("ar_description") %></label>
                    <%= form.text_field :description_ar, :class => "form-control", :placeholder => t("ar_description"), :required => true %>
                </div>

                <div class="form-group">
                  <label for="exampleInputdetails"><%= t("en_description") %></label>
                    <%= form.text_field :description_en, :class => "form-control", :placeholder => t("en_description"), :required => true %>
                </div>

                <div class="checkbox">
                  <label for="exampleInputstatus"><%= t("Status") %></label>
                    <%= form.check_box :status,{},"true","false" %>                  
                </div>

                <div class="form-group">
                  <label><%= t("Image") %></label>
                  <%= form.file_field :image %>
                </div>

              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                    <button type="submit" class="btn btn-primary" id="submit" >Submit</button>
              </div>
            <% end %>
          </div>
      </div>
  </div>
</section>


<%= link_to 'Back', admin_premium_customers_path %>


<script language="JavaScript" type="text/javascript" src="/js/jquery-3.3.1.min.js"></script>

<script>
    $(document).ready(function() {
      $('#premium_customer_category').val("<%= params[:type] %>");
        });
</script>

app/views/admin/premium_customers/show.html.erb
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">          
        <div class="box-header">
          <h3 class="box-title">
          <% if @premium_customer.category == "our_partners" %>
            <%= t("our_partners") %></h3>
          <% else %>
            <%= t("customer_opinions") %></h3>
          <% end %>
        </div><br>
          
        <!-- /.box-header -->
        <div class="box-body">
          <table id="example2" class="table table-bordered table-hover">
            <thead></thead>
              <tbody>
              <tr>
                  <td><%= t("category") %></td>
                  <td><%= @premium_customer.category %></td>                      
                </tr>
                <tr>
                  <td><%= t("Key") %></td>
                  <td><%= @premium_customer.key %></td>                      
                </tr>
                <tr>
                  <td><%= t("ar_name") %></td>
                  <td><%= @premium_customer.name_ar %></td>                      
                </tr>
                <tr>
                  <td><%= t("en_name") %></td>
                  <td><%= @premium_customer.name_en %></td>                      
                </tr>
                <tr>
                  <td><%= t("ar_description") %></td>
                  <td><%= @premium_customer.description_ar %></td>                      
                </tr>
                <tr>
                  <td><%= t("en_description") %></td>
                  <td><%= @premium_customer.description_en %></td>                      
                </tr>
                <tr>
                  <td><%= t("Status") %></td>
                  <td><%= @premium_customer.status %></td>                      
                </tr>
                <tr>
                  <td><%= t("Image") %></td>
                  <% if @premium_customer.image.attached? %>                
                    <td>
                      <%= image_tag @premium_customer.image.variant(resize: "100x100!") %> 
                      <a href="<%= Rails.application.credentials[:app_host]%>/admin/delete_customer_image/?id=<%= @premium_customer.id%>">delete image</a><br><br>
                    </td> 
                  <% end %>     
                </tr>         
                <tr>
                  <td><%= t("created_at") %></td>
                  <td><%= @premium_customer.created_at %></td>                      
                </tr>
                <tr>
                  <td><%= t("updated_at") %></td>
                  <td><%= @premium_customer.updated_at %></td>                      
                </tr>
                </tbody> 
              </table>
            </div>
          </div>
        </div>
    </div>
  </section>


<%= link_to t('Edit'), edit_admin_premium_customer_path(@premium_customer) %> |
<%= link_to t('Back'), admin_premium_customers_path %>