config/routes.rb
Rails.application.routes.draw do
  
  
  resources :errors_logs
  resources :tickets
  resources :basic_data
  
  root 'pages#homepage'
  get 'pages/visitor_login'
  get 'pages/home'
  get 'pages/contact_us'
  get 'pages/mission'
  get 'pages/about_us'
  get 'pages/human_cadres'
  get 'pages/services'
  get 'pages/customers'
  get 'pages/news'
  get 'pages/details'
  get 'pages/our_company'
  get 'pages/disclaimer'
  get 'pages/terms_of_use'
  get 'pages/privacy_policy'
  get 'pages/change_lang'
  get 'pages/error'
  


  
  get "unlockaccount" => "users#unlockaccount"

  resources :visitor_services, only: [:new, :create]
  resources :users, except: [:index,:destroy]
  resources :audit_logs, only: [:create]
 
  get 'edit_password' => "users#edit_password"
  match 'confirm_signin', to: 'users#confirm_signin', via: %i(get post)
  get 'resend_code' => "users#resend_confirmation_code"
  get 'models' => "users#models"
  get 'reports' => "users#reports"
  get 'required_files' => "users#required_files"
  patch 'update_file' => "users#update_file"
  get 'notifications' => "users#notifications"
  get 'show_notification' => "users#show_notification"
  post 'send_email' => "visitor_services#send_email"



  


  #scope path: 'admin', module: 'admin' do
  namespace :admin do
    match 'add-user', to: 'members#add_user', via: %i(get post)
    get 'admins' => "members#admins"
    get 'users/search' => "members#user_search"
    get 'admins/search' => "members#admin_search"
    get 'visitor_services/search' => "visitor_services#search"
    get 'messages/search' => "messages#ticket_search"
    get 'dashboard' => "pages#dashboard"
    #get 'news' => "pages#news"

    get 'delete_image' => "contents#delete_image"
    get 'delete_news_image' => "news#delete_news_image"
    get 'delete_mission_image' => "our_missions#delete_mission_image"
    get 'delete_customer_image' => "premium_customers#delete_customer_image"





    #resources :users
    resources :audit_logs, only: [:index, :show]
    resources :visitor_services
    resources :contents, except: [:new, :create, :destroy]
    resources :premium_customers
    resources :our_missions, except: [:new, :create, :destroy]
    resources :news
    resources :models
    resources :required_files
    resources :users_basic_data
    resources :reports
    resources :members
    resources :messages
    resources :notifications






  end
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :required_file , foreign_key: "user_id"
  has_many :report , foreign_key: "user_id"
  has_many :notification , foreign_key: "user_id"
  has_many :ticket , foreign_key: "user_id"
  has_many :basic_datum , foreign_key: "user_id"
  has_many :audit_log , foreign_key: "user_id"

  enum role_id: { user: 0, admin: 1 }
  enum active: { Active: 1, Disabled: 0}
  enum company_type: { Business_Administration: 1, Accounting: 2 }

  validates :email, uniqueness: true, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :password, length: 8..20, presence: true, if: :should_validate_password?
  validates :username, length: { maximum: 30 }, presence: true
  validates :address, :company_type, :company_activity, :admin_name, :admin_job, :phone, :fax, length: { maximum: 100 }

  validates_inclusion_of :role_id, :in => ['user', 'admin'], :allow_nil => false
  validates_inclusion_of :active, :in => ['Active', 'Disabled'], :allow_nil => false

 



  def should_validate_password?
    password.present?
  end

  


end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new", layout: false

  end

  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login , except: [:new, :create, :unlockaccount]
  skip_before_action :check2fa ,only: [:new, :destroy, :create, :unlockaccount]
  layout 'user'


  # GET /users/1
  # GET /users/1.json
  def show
    unless (current_user.role_id == "admin" or current_user.id == @user.id)
      redirect_to root_path, notice: 'Not allowed.' 
    end
  end

  # GET /users/new
  def new
    @user = User.new
    render layout: false
  end


  # GET /users/1/edit
  def edit
    unless (current_user.id == @user.id)
      redirect_to root_path, notice: 'Not allowed.' 
    end
  end

  def edit_password
    @user = User.find(current_user.id)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.active = "Disabled"
    @user.role_id = "user"

    #respond_to do |format|
      if @user.save
        UserMailer.new_account(@user.email,@user.username).deliver_later
        AuditLog.create(user_id: @user.id, added_by: @user.id, foreign_id: @user.id, action_type: "create account", meta_data: "New User has been registerd", ip_address: request.remote_ip, user_agent: request.user_agent)
        redirect_to sign_in_path, notice: t('account_created_waiting_admin_confirm')
        #format.html { redirect_to @user, notice: 'User was successfully created.' }
        #format.json { render :show, status: :created, location: @user }
      else
        render :new, layout: false, notice: @user.errors 
        #redirect_to sign_up_path, notice: @user.errors
        #format.html { render :new, layout: false, notice: @user.errors }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    unless (current_user.id == @user.id)
      redirect_to root_path, notice: 'Not allowed.' 
    else
      @user = User.authenticate(current_user.email,params[:user][:confirm_password])
        if !(@user)
          if (params[:user][:password])
            redirect_to edit_password_path , notice: t("wrong password confirmation") and return
          else
            redirect_to edit_user_path(params[:id]) , notice: t("wrong password confirmation") and return
          end
        else
          respond_to do |format|
            if @user.update(user_params)
              format.html { redirect_to @user, notice: t('Data was successfully updated') }
              format.json { render :show, status: :ok, location: @user }
            else
              format.html { render :edit }
              format.json { render json: @user.errors, status: :unprocessable_entity }
            end
          end
        end
    end
  end

  # after user sign in, he redirected to this page to confirm signin.
  # user should enter the code which has been sent to his email or his google code.
  # to check the correctness of the entered code.
  # @param [String] code
  # @param [String] token_code
  def confirm_signin
    if request.method == 'GET'
      render :layout => false
      session[:verify_code] = false
      #render :layout => false
    elsif request.method == 'POST'
      @user = current_user 
      session[:verify_code] = false
      @user_code = params[:confirm][:code]
      @sent_code = session[:token_code]
      if (@user_code == @sent_code) 
        session[:verify_code] = true
        if @user.role_id == "admin"
          redirect_to admin_dashboard_path, notice: "Welcome back!"
        else
          redirect_to @user, notice: "Welcome back!"
        end
      else 
        redirect_to confirm_signin_path, notice: "wrong code!" 
      end 
    end    
  end


  def resend_confirmation_code
    if (session[:token_code] != nil and session[:token_code] != "")
      @token = session[:token_code]
    else
      @token = SecureRandom.hex(4)
    end
    UserMailer.confirmsignin(current_user.email,current_user.username,@token).deliver_later
    redirect_to confirm_signin_path, notice: t("code_resended")
  end

  # after number of failed login attempts, user's account will be disabled and link will be send to user's mail. 
  # when the user click the link, he is redirected here to unlock account and allow him to signin again. 
  # @param [Integer] user_id 
  # @param [String] token 
  def unlockaccount
    @id = params[:id]
    @token = params[:token]
    @user = User.where("id =?",@id ).first
    if @token  == @user.unlock_token      
       @user.failed_attempts = 0
       @user.locked = 0
       @user.unlock_token = ""
       if @user.save
        flash.now.notice = t('your_account_unlocked')
       end
       render template: "sessions/new",  layout: false
    else
      flash.now.notice = 'InValid Token .'
      render template: "sessions/new" ,layout: false 
    end
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def models
    @models = Model.where("status =? ", true).all
  end

  def reports
    @reports = Report.where("user_id =? ", current_user.id).all
  end


  def required_files
    @required_files = RequiredFile.where("user_id =? ", current_user.id).all
  end

  def update_file
    @required_files = RequiredFile.where("id =? ", params[:required_file][:id]).first
    if @required_files
      if @required_files.update(:status => "pending", :file => params[:required_file][:file])
        AuditLog.create(user_id: current_user.id, added_by: current_user.id, foreign_id: @required_files.id, action_type: "Edit required file", meta_data: "Required file was updated", ip_address: request.remote_ip, user_agent: request.user_agent)
        redirect_to required_files_path, notice: 'Required file was successfully updated.'
      else
        render :required_files 
      end
    end
  end

  def notifications
    @notifications = Notification.where("user_id =? ", current_user.id).all
  end


  def show_notification
    @notification = Notification.where("id =? ", params[:id]).first
    @notification.update(seen: true)

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :phone, :address, :role_id, :active, :locked, :sign_in_count, :failed_attempts, :unlock_token, :company_type, :company_activity, :fax, :admin_name, :admin_job)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def format_link(request)
        request.protocol + request.host
    end
end

app/views/users/add_user.html.erb
<%= form_for @user , :url => add_user_path do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: 
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' , :required => true %>
  </div>
  <div class="text-field">
    <%= form.label :username %>
    <%= form.text_field :username, :required => true %>
  </div>
  <div class="text-field">
    <%= form.label :role_id %>
    <%= form.select(:role_id, options_for_select([["user","user"],["admin","admin"]]), {},:class => 'form-control',:include_blank =>  'choose from list')%>
  </div>
  <div class="text-field">
    <%= form.label :active %>
    <%= form.check_box :active,{},"Active","Disabled" %>    
  </div>   
  <div class="form-group row m-t-md">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-fw primary" id="submit" >Submit</button>
    </div>
  </div>
<% end %>

<%= link_to 'back', root_path %>

app/views/users/admin_search.html.erb
<%= form_tag  url_for(:controller => 'users', :action => 'admin_search'), :method => 'get' do %>
  <div class="row">
    <div class="col-lg-2">    
      <input type="text" name="usernamesearch" class="form-control" placeholder="<%= 'username' %>" >
    </div>
    <div class="col-lg-2">    
      <input type="text" name="emailsearch" class="form-control" placeholder="<%= 'Email' %>" >
    </div>
    <div class="col-lg-2">    
      <input type="text" name="phonesearch" class="form-control" placeholder="<%= 'phone' %>" >
    </div>
    <div class="col-lg-2">
      <%= select_tag(:active, options_for_select([['Active','Active'],['Disabled','Disabled']]),:include_blank => 'Account Status')   %>
    </div>
  </div><br>   
  <button type="submit"  class="btn btn-primary waves-effect waves-light  text-center" style="margin:auto !important;"><%= 'search' %> </button>  
<% end %>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.username %></td>
        <td><%= admin.email %></td>
        <td><%= admin.phone %></td>
        <td><%= admin.address %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_user_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'back', root_path %>


<%# link_to 'New User', new_admin_path %>

app/views/users/confirm_signin.html.erb
<!-- <h2> Email Code Authentication </h2>
  <%# form_for :confirm , :url => confirm_signin_path do |form| %>
	<div class="text-field">
      <label>Authentication Code</label><br>
		<%# form.text_field :code , :required => true %>
    </div>              
    <div class="submit-field">
      <%# form.submit %>
    </div>
  <%# end %><br>    
<div><%# button_to "Sign Out", sign_out_path, method: :delete, class: "text-primary _600" %></div> -->		

<!DOCTYPE html>
  <html lang="en" dir="ltr">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Progress Pioneers</title>
      <link rel="stylesheet" href="<%= Rails.application.credentials[:app_host]%>/site/css/bootstrap.min.css">
      <link rel="stylesheet" href="<%= Rails.application.credentials[:app_host]%>/site/css/main.css">
      <link rel='stylesheet' href='<%= Rails.application.credentials[:app_host]%>/site/css/font-awesome.min.css'/>
      <link rel="stylesheet" href="<%= Rails.application.credentials[:app_host]%>/site/css/media.css">
    </head>
    <body>
    <section class="limiter2 text-center">
      <div class="limiter-overlay">
        <div class="container-login1002">
          <div  class="modal-body" id="flash">
            <% flash.each do |name, msg| %>
              <div class="row msg-alert2 alert box-size border-color-brand hlf-btm bg-white padding-ver-xs clearfix">
                <button  class="col-lg-1 font-bold" type="button" class="close" data-dismiss="modal" id="close">&times;</button>
                  <h6 class="col-lg-10" class="font-bold"><%= content_tag :div, msg, :id => "flash_#{name}" %></h6>
                  <i class="fa fa-close" class="col-lg-1" style="color:red;"></i>
              </div>
            <% end %>
          </div>        
          <div class="wrap-login100" style="position:fixed">
            <%= form_for :confirm , :url => confirm_signin_path, :html => {:class => 'login100-form validate-form'} do |form| %>
              <span class="login100-form-title p-b-26">
                <%= t("confirm_signin")%>
              </span>
              <span class="login100-form-title p-b-48">
                <i class="zmdi zmdi-font"></i>
              </span>
              <div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
                <%= form.text_field :code,  :class => "input100" , :required => true,  :autocomplete => :off  %>
                <span class="focus-input100" data-placeholder="<%= t("confirmation_code")%>"></span>
              </div>
              <div class="container-login100-form-btn">
                <div class="wrap-login100-form-btn">
                  <div class="login100-form-bgbtn"></div>
                  <button type="submit" class="login100-form-btn">
                    <%= t("Send")%>
                  </button>
                </div>
              </div>
              <div class="new-text">
                <span class="txt1">
                  <%= link_to t("resendcode"), resend_code_path, class: "txt2" %>
                </span>
              </div>
              <div class="row">
                <div class="footer-bottom1">
                  <ul>
                    <li><a href="<%= Rails.application.credentials[:app_host]%>/pages/privacy_policy" id="ctrl_footer_master_rptFooterLinks_ctl00_lnkFooter"><%= t("privacy policy") %></a> </li>
                    <li><a href="<%= Rails.application.credentials[:app_host]%>/pages/terms_of_use" id="ctrl_footer_master_rptFooterLinks_ctl01_lnkFooter"><%= t("terms of use") %></a> </li>
                    <li><a href="<%= Rails.application.credentials[:app_host]%>/pages/disclaimer" id="ctrl_footer_master_rptFooterLinks_ctl01_lnkFooter"><%= t("disclaimer") %></a> </li>
                  </ul>
                  <p class="copy_right">
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> <span>Progress</span> Organization All rights reserved
                  </p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
    <script src="<%= Rails.application.credentials[:app_host]%>/site/js/jquery-3.3.1.min.js"></script>
    <script src="<%= Rails.application.credentials[:app_host]%>/site/js/popper.min.js"></script>
    <script src="<%= Rails.application.credentials[:app_host]%>/site/js/bootstrap.min.js"></script> 
    <script src="<%= Rails.application.credentials[:app_host]%>/site/js/main.js"></script>
  </body>
</html>

		

app/views/users/edit.html.erb
<!-- Main content -->
<section class="content">
  <div class="box-header with-border with-border4 box--header">
    <div class="box box-info">
      <div class="box-header with-border with--border">
        <h3 class="box-title"><%= t("Edit Data") %> </h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <div class="row">
        <div class="col-lg-6">
          <%= form_for @user, :html => { :class => "form-horizontal" } do |form| %>
            <% if @user.errors.any? %>
              <div id="error_explanation">
                <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: 
                  <ul>
                    <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
              </div>
            <% end %>
            <div class="box-body">
              <div class="form-group row">
                <div class="col-lg-6">
                  <label for="inputEmail3" class=" control-label"><%= t("Email") %></label>
                </div>
                <div class="col-lg-6">
                  <%= form.text_field :email, type: 'email', class: "form-control", placeholder: t("Email") %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-lg-6">
                  <label for="inputEmail3" class="control-label"><%= t("Company Name") %></label>
                </div>
                <div class="col-lg-6">
                  <%= form.text_field :username, class: "form-control", placeholder: t("Company Name")  %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-lg-6">
                  <label for="inputEmail3" class=" control-label"><%= t("Company Type") %></label>
                </div>
                <div class="col-lg-6">
                  <%= form.select(:company_type, options_for_select([[t("Business Administration"),"Business_Administration"],[t("Accounting"),"Accounting"]], :selected => form.object.company_type), {},:class => 'form-control select2',:include_blank =>  'choose from list')%>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-lg-6">
                  <label for="inputEmail3" class=" control-label"><%= t("Main Company Address") %></label>
                </div>
                <div class="col-lg-6">
                   <%= form.text_field :address, class: "form-control", placeholder: t("Main Company Address")  %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-lg-6">
                  <label for="inputEmail3" class=" control-label"><%= t("Company Activites") %></label>
                </div>
                <div class="col-lg-6">
                  <%= form.text_field :company_activity, class: "form-control", placeholder: t("Company Activites")  %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-lg-6">
                  <label for="inputEmail3" class=" control-label"><%= t("Phone") %></label>
                </div>
                <div class="col-lg-6">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <%= form.text_field :phone, class: "form-control", 'data-inputmask' =>' &quot;mask&quot;: &quot;(999) 999-9999&quot;' , 'data-mask'=>''  %>
                  </div>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-lg-6">
                  <label for="inputEmail3" class=" control-label"><%= t("Fax") %></label>
                </div>
                <div class="col-lg-6">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <%= form.text_field :fax, class: "form-control", 'data-inputmask' =>' &quot;mask&quot;: &quot;(999) 999-9999&quot;' , 'data-mask'=>''  %>
                  </div>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-lg-6">
                  <label for="inputEmail3" class=" control-label"><%= t("Adminstrator name") %></label>
                </div>
                <div class="col-lg-6">
                  <%= form.text_field :admin_name, class: "form-control", placeholder: t("Adminstrator name")  %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-lg-6">
                  <label for="inputEmail3" class=" control-label"><%= t("Adminstrator job") %></label>
                </div>
                <div class="col-lg-6">
                  <%= form.text_field :admin_job, class: "form-control", placeholder: t("Adminstrator job")  %>
                </div>
              </div>            
              <div class="form-group row">
                <div class="col-lg-6">
                  <label for="inputEmail3" class=" control-label"><%= t("Password") %></label>
                </div>
                <div class="col-lg-6">
                  <%= form.password_field :confirm_password, :required => true,class: 'form-control' %>
                </div>
              </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
              <button type="submit" class="btn btn-info pull-left"><%= t("Edit") %></button>
            </div>
          <!-- /.box-footer -->
          <% end %>
        </div>
        <div class="col-lg-6 imgg">
          <img src="<%= Rails.application.credentials[:app_host]%>/user/dist/img/accounting-achievement-aerial-1043506.jpg" alt="">
        </div>
      </div>
    </div>
  </div>
</section>
<%= link_to 'show', user_path(@user) %> |

app/views/users/edit_password.html.erb
<!-- Main content -->
<section class="content">
  <div class="box-header with-border with-border4 box--header">
    <div class="box box-info">
      <div class="box-header with-border with--border">
        <h3 class="box-title"><%= t("Edit Password") %> </h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <div class="row">
        <div class="col-lg-6">
          <%= form_for @user, :html => { :class => "form-horizontal" } do |form| %>
            <% if @user.errors.any? %>
              <div id="error_explanation">
                <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: 
                  <ul>
                    <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
              </div>
            <% end %>
            <div class="box-body">
              <div class="form-group row">
                <div class="col-lg-6">
                  <label class=" control-label"><%= t("New Password") %></label>
                </div>
                <div class="col-lg-6">
                  <%= form.password_field :password, :required => true,class: 'form-control' %>
                </div>
              </div>     
              <div class="form-group row">
                <div class="col-lg-6">
                  <label class=" control-label"><%= t("Current Password") %></label>
                </div>
                <div class="col-lg-6">
                  <%= form.password_field :confirm_password, :required => true,class: 'form-control' %>
                </div>
              </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
              <button type="submit" class="btn btn-info pull-left"><%= t("Edit") %></button>
            </div>
          <!-- /.box-footer -->
          <% end %>
        </div>
        <div class="col-lg-6 imgg">
          <img src="<%= Rails.application.credentials[:app_host]%>/user/dist/img/accounting-achievement-aerial-1043506.jpg" alt="">
        </div>
      </div>
    </div>
  </div>
</section>
<%= link_to 'show', user_path(@user) %> |

app/views/users/index.html.erb
<%= form_tag  url_for(:controller => 'users', :action => 'user_search'), :method => 'get' do %>
  <div class="row">
    <div class="col-lg-2">    
      <input type="text" name="usernamesearch" class="form-control" placeholder="<%= 'username' %>" >
    </div>
    <div class="col-lg-2">    
      <input type="text" name="emailsearch" class="form-control" placeholder="<%= 'Email' %>" >
    </div>
    <div class="col-lg-2">    
      <input type="text" name="phonesearch" class="form-control" placeholder="<%= 'phone' %>" >
    </div>
    <div class="col-lg-2">
      <%= select_tag(:active, options_for_select([['Active','Active'],['Disabled','Disabled']]),:include_blank => 'Account Status')   %>
    </div>
  </div><br>   
  <button type="submit"  class="btn btn-primary waves-effect waves-light  text-center" style="margin:auto !important;"><%= 'search' %> </button>  
<% end %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'back', root_path %>


<%# link_to 'New User', new_user_path %>

app/views/users/user_search.html.erb
<%= form_tag  url_for(:controller => 'users', :action => 'user_search'), :method => 'get' do %>
  <div class="row">
    <div class="col-lg-2">    
      <input type="text" name="usernamesearch" class="form-control" placeholder="<%= 'username' %>" >
    </div>
    <div class="col-lg-2">    
      <input type="text" name="emailsearch" class="form-control" placeholder="<%= 'Email' %>" >
    </div>
    <div class="col-lg-2">    
      <input type="text" name="phonesearch" class="form-control" placeholder="<%= 'phone' %>" >
    </div>
    <div class="col-lg-2">
      <%= select_tag(:active, options_for_select([['Active','Active'],['Disabled','Disabled']]),:include_blank => 'Account Status')   %>
    </div>
  </div><br>   
  <button type="submit"  class="btn btn-primary waves-effect waves-light  text-center" style="margin:auto !important;"><%= 'search' %> </button>  
<% end %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'back', users_path %>


<%# link_to 'New User', new_user_path %>