config/routes.rb
Rails.application.routes.draw do
  
  
  resources :errors_logs
  resources :tickets
  resources :basic_data
  
  root 'pages#homepage'
  get 'pages/visitor_login'
  get 'pages/home'
  get 'pages/contact_us'
  get 'pages/mission'
  get 'pages/about_us'
  get 'pages/human_cadres'
  get 'pages/services'
  get 'pages/customers'
  get 'pages/news'
  get 'pages/details'
  get 'pages/our_company'
  get 'pages/disclaimer'
  get 'pages/terms_of_use'
  get 'pages/privacy_policy'
  get 'pages/change_lang'
  get 'pages/error'
  


  
  get "unlockaccount" => "users#unlockaccount"

  resources :visitor_services, only: [:new, :create]
  resources :users, except: [:index,:destroy]
  resources :audit_logs, only: [:create]
 
  get 'edit_password' => "users#edit_password"
  match 'confirm_signin', to: 'users#confirm_signin', via: %i(get post)
  get 'resend_code' => "users#resend_confirmation_code"
  get 'models' => "users#models"
  get 'reports' => "users#reports"
  get 'required_files' => "users#required_files"
  patch 'update_file' => "users#update_file"
  get 'notifications' => "users#notifications"
  get 'show_notification' => "users#show_notification"
  post 'send_email' => "visitor_services#send_email"



  


  #scope path: 'admin', module: 'admin' do
  namespace :admin do
    match 'add-user', to: 'members#add_user', via: %i(get post)
    get 'admins' => "members#admins"
    get 'users/search' => "members#user_search"
    get 'admins/search' => "members#admin_search"
    get 'visitor_services/search' => "visitor_services#search"
    get 'messages/search' => "messages#ticket_search"
    get 'dashboard' => "pages#dashboard"
    #get 'news' => "pages#news"

    get 'delete_image' => "contents#delete_image"
    get 'delete_news_image' => "news#delete_news_image"
    get 'delete_mission_image' => "our_missions#delete_mission_image"
    get 'delete_customer_image' => "premium_customers#delete_customer_image"





    #resources :users
    resources :audit_logs, only: [:index, :show]
    resources :visitor_services
    resources :contents, except: [:new, :create, :destroy]
    resources :premium_customers
    resources :our_missions, except: [:new, :create, :destroy]
    resources :news
    resources :models
    resources :required_files
    resources :users_basic_data
    resources :reports
    resources :members
    resources :messages
    resources :notifications






  end
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
    has_one_attached :file
    belongs_to :user ,:foreign_key => "user_id"


end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::AdminController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to admin_report_path(@report), notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to admin_report_path(@report), notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to admin_reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :user_id, :file)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/admin/reports/_form.html.erb
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-6">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t("New Report")%></h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <%= form_for @report , :url => admin_reports_path do |form| %>
          <% if @report.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@report.errors.count, "error") %> prohibited this required_file from being saved:</h2>
                <ul>
                  <% @report.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
            </div>
          <% end %>
          <div class="box-body">
            <div class="form-group">
              <label><%= t("Name") %></label>
              <%= form.select(:user_id,  options_for_select(User.where(:role_id => "user").all.collect {|p| [ p.email, p.id ] }) ,{:include_blank =>  'choose from list'} ,  :class => 'form-control' ) %>
            </div>
            <div class="form-group">
              <label><%= t("details") %></label>
              <%= form.text_field :name, :class => "form-control", :placeholder => t("Details"), :required => true %>
            </div>
            <div class="form-group">
              <label><%= t("Attachment") %></label>
                <%= form.file_field :file, :class => "form-control"%>
            </div>
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <button type="submit" class="btn btn-primary" id="submit" >Submit</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/admin/reports/edit.html.erb
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-6">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t("Edit Report Details")%></h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <%= form_for @report , :url => admin_report_path do |form| %>
          <% if @report.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>
                <ul>
                  <% @report.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
            </div>
          <% end %>
          <div class="box-body">
            <div class="form-group">
              <label><%= t("UserName") %></label>
               <%= form.select(:user_id, options_for_select(User.where(:role_id => "user").all.collect {|p| [ p.email, p.id ] }, :selected => form.object.user_id), {},:class => 'form-control')%>
            </div>
            <div class="form-group">
              <label><%= t("Name") %></label>
              <%= form.text_field :name, :class => "form-control", :placeholder => t("Name"), :required => true %>
            </div>
            <div class="form-group">
              <label><%= t("Attachment") %></label>
                <%= form.file_field :file, :class => "form-control"%>
                <%= @report.file.filename %>
            </div>            
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <button type="submit" class="btn btn-primary" id="submit" >Submit</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>


<%= link_to t('Show'), admin_report_path(@report) %> |
<%= link_to t('Back'), admin_reports_path %>

app/views/admin/reports/index.html.erb
 <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
          
            <div class="box-header">
              <h3 class="box-title"><%= t("Reports") %></h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th><%= t("User") %></th>
                  <th><%= t("Name") %></th>                  
                  <th><%= t("file") %></th>
                  <th><%= t("created_at") %></th>
                  <th><%= t("updated_at") %></th>
                  <th colspan="3"></th>
                </tr>
                </thead>
                <tbody>
                  <% @reports.each do |report| %>
                    <tr>
                      <td><%= report.user.username %></td>
                      <td><%= report.name %></td>
                      <% if report.file.attached? %>
                        <td><%= link_to "download", rails_blob_path(report.file, disposition: 'download') %></td>
                      <% else %>
                         <td></td>
                      <% end %>
                      <td><%= report.created_at.strftime('%H:%M:%S%p at %d/%m/%Y ') %></td>
                      <td><%= report.updated_at.strftime('%H:%M:%S%p at %d/%m/%Y ') %></td>
                      <td><%= link_to t("Show"), admin_report_path(report) %></td>
                      <td><%= link_to t("Edit"), edit_admin_report_path(report) %></td>
                      <td><%= link_to t("Destroy"), admin_report_path(report), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>               
                </tbody> 
              </table>
            </div>
          </div>
        </div>
      </div>
  </section>


<br>
<%= link_to t('Back'), admin_dashboard_path %>| <%= link_to  t("New Report"), new_admin_report_path %>

app/views/admin/reports/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_reports_path %>

app/views/admin/reports/show.html.erb
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">      
        <div class="box-header">
          <h3 class="box-title"><%= t("Details") %></h3>
        </div>
        <br>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="example2" class="table table-bordered table-hover">
            <thead></thead>
            <tbody>
                <tr>
                  <td><%= t("Name") %></td>
                  <td><%= @report.name  %></td>                      
                </tr>
                <tr>
                  <td><%= t("User") %></td>
                  <td><%= @report.user.username %></td>                      
                </tr>
                <tr>
                  <td><%= t("file") %></td>
                  <td><%= link_to "download", rails_blob_path(@report.file, disposition: 'download') %></td>                      
                </tr>
                <tr>
                  <td><%= t("created_at") %></td>
                  <td><%= @report.created_at %></td>                      
                </tr>
                <tr>
                  <td><%= t("updated_at") %></td>
                  <td><%= @report.updated_at %></td>                      
                </tr>
                <tr>
                  <td></td>
                  <td><%= link_to t('Edit'), edit_admin_report_path(@report) %> | 
                      <%= link_to t('Back'), admin_reports_path %>
                  </td>                      
                </tr>
            </tbody> 
          </table>
        </div>
      </div>
    </div>
  </div>
</section>